### ISSUE TITLE
Godot 4.1.1版本插件无法使用

### ISSUE THREAD

**Issue by Xuhui-Yan** [kaluluosi/GDEexcelExporer-Plugin#1]
你好作者，我在安装此插件时，并尝试在系统设置里启用时，遇到了如下警告：
Unable to load addon script from path: 'res://addons/GDExcelExporter/plugin.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/GDExcelExporter/plugin.cfg' to prevent further errors.
我已经按照GDExcelExporter的安装步骤，到了创立settings文件夹这里，并在尝试安装一键启动插件时遇到了此问题。是否可能和自动生成的settings文件夹有关？（因为看到生成的settings文件夹首字母为小写，而安装演示中为大写，是否会影响gd脚本的正确性？）
希望能得到您的解答，非常感谢

**Comment by kaluluosi** [comment]
4.0 插件的写法有点不一样，这个插件好久没更新了。
后面我更新一下，顺便加个一键导出和重导入配置脚本的功能。

**Comment by Xuhui-Yan** [comment]
非常感谢你的回复

**Comment by kaluluosi** [comment]
@Xuhui-Yan  master分支已经提交了 Godot 4.0 的支持
1. 新增了右上角的Excel一键导出按钮
2. 完善了README.md的说明

**Comment by Xuhui-Yan** [comment]
> @Xuhui-Yan  master分支已经提交了 Godot 4.0 的支持
> 
> 1. 新增了右上角的Excel一键导出按钮
> 
> 2. 完善了README.md的说明

感谢大佬
